version: "3.8"
services:
  nginx:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${APPLICATION_NAME}-nginx
    restart: always
    build:
      context: ./nginx
    ports:
      - "80:80"
  api:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${APPLICATION_NAME}-api
    build:
        context: ./api
    volumes:
      - /app/node_modules
      - ./api:/app
    env_file:
      - ./api/dev.env
    ports:
      - "5000:5000"
  client:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/${APPLICATION_NAME}-client
    build:
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - "3000:3000"
