version: "3.8"
services:
  api:
    image: 382707088245.dkr.ecr.ap-northeast-2.amazonaws.com/test-api
    build:
        context: ./api
    volumes:
      - /app/node_modules
      - ./api:/app
    ports:
      - "5000:5000"
